logger:
    file: /var/log/open5gs/pgw.log
    trace:
        app: 1
        diameter: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

pgw:
    freeDiameter: /etc/freeDiameter/pgw.conf
    gtpc:
      - addr: 127.0.0.3
    gtpu:
      - addr: 127.0.0.3
    ue_pool:
      - addr: 45.45.0.1/16
        apn: "internet"
        dev: "ogstun"
    dns:
      - 8.8.8.8
      - 8.8.4.4
